SELECT TOP (10) [ScrSSN]
      ,[PatientSID]
      ,[VisitSID]
      ,[VisitDate]
      ,[CIHType]
      ,[Sta6a]
      ,[Tele]
      ,[PrimaryStopCode]
      ,[SecondaryStopCode]
      ,[CPT]
      ,[CPT_num_terms]
      ,[CPT_codes]
      ,[NT]
      ,[NT_num_terms]
      ,[NT_terms]
      ,[NT_inclusions]
      ,[LocName]
      ,[LocationName]
      ,[LN_inclusions]
      ,[HF]
      ,[HF_num_terms]
      ,[HF_terms]
      ,[HF_inclusions]
      ,[StopCode]
      ,[strong_evid]
      ,[weak_evid]
  INTO [OPCCCT_CIH].[Dflt].[access_test]
  FROM [OPCCCT_CIH].[Dflt].[acupuncture_patient_list]

