SELECT TOP (1000) [TableId]
      ,[VisitSID]
      ,[VisitDateTime]
      ,[LastModifiedDateTime]
      ,[NoncountClinicFlag]
      ,[EncounterType]
      ,[PatientStatusInOut]
      ,[AppointmentStatus]
      ,[AppointmentType]
      ,[Sta3n]
      ,[InstitutionName]
      ,[StaPa]
      ,[StaPaName]
      ,[VISN]
      ,[REGION]
      ,[DivisionName]
      ,[Sta6a]
      ,[LocationName]
      ,[LocationType]
      ,[PrimaryStopCode]
      ,[Primary_Name]
      ,[SecondaryStopCode]
      ,[SecondaryName]
      ,[NationalChar4]
      ,[NationalChar4Description]
      ,[StaffSID]
      ,[PositionTitle]
      ,[ProviderSID]
      ,[ProviderType]
      ,[PatientSID]
      ,[PatientICN]
      ,[Age]
      ,[Gender]
      ,[SrcSystem]
      ,[SrcCHAR4]
      ,[SrcArcCPT1]
      ,[SrcArcCPT2]
      ,[SrcArcCPT3]
      ,[SrcHF]
      ,[SrcMOVE1]
      ,[SrcMOVE2]
      ,[SrcSTOP1]
      ,[SrcSTOP2]
      ,[LoadDate]
  FROM [OPCCCT_Analytics].[DOEx].[WholeHealth_1_VISITS]

  select distinct nationalchar4
  ,count(*) as record_count
  from [OPCCCT_Analytics].[DOEx].[WholeHealth_1_VISITS]
  where VisitDateTime >= '2022-10-01' and VisitDateTime < '2026-10-01'
  group by nationalchar4

  /* investigate the stop codes*/
  select distinct [SecondaryStopCode], [SecondaryName]
  ,count(*) as record_count
  from [OPCCCT_Analytics].[DOEx].[WholeHealth_1_VISITS]
  where VisitDateTime >= '2022-10-01' and VisitDateTime < '2026-10-01'
  group by [SecondaryStopCode], [SecondaryName]